# Welcome to elblogdebraian Jekyll Theme!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

theme_version: 1.0.4

# Site settings
title:              El Blog de Braian
logo:               /images/logos/elblogdebraian2.png
description:        Thoughts, Stories and Ideas
baseurl:            '' # The subpath of your site, e.g. /blog
url:                'https://elblogdebraian.github.io' # The base hostname & protocol for your site
twitter:            https://twitter.com/n00b2h4ck3r
facebook:           https://www.facebook.com/braianagustin.diez
instagram:          https://www.instagram.com/elblogdebraian

markdown:  kramdown
permalink: pretty
paginate:  11
sass:
  style: compressed

gems:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

# Authors
authors:
  Braian A. Diez:
    name:     Braian A. Diez
    bio:      Diseñador & Blogger. Minimalista. Quiero ser una persona a la cual en algún momento reconozcan por haber cambiado la vida de miles de jóvenes y no ser reconocido por haber vivido a Jesús desde el banco de suplentes.
    gravatar: https://secure.gravatar.com/avatar/713f0634508cc8fd29f98ff6d84d86af?s=150
    email:    bdiez19@gmail.com
    facebook:  https://www.facebook.com/braianagustin.diez
    instagram:   https://www.instagram.com/elblogdebraian
    twitter:  https://twitter.com/n00b2h4ck3r