baseURL = "/"
disableLanguages = []
disqusShortname = "n00b2h4ck3r"
paginate = "3"
summaryLength = "20"
theme = "gojournal"
title = "elblogdebraian | un blog para encontrarse con Dios"
[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com)"
home = "Home"
languageCode = "en-us"
languageName = "En"
subscription_content = "Subscribe now to get notified about exclusive News And Views Issues every week!"
subscription_title = "Join Newteller for the latest news"
weight = 2
[Languages.es]
contentDir = "content/spanish"
copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com)"
home = "Inicio"
languageCode = "es-es"
languageName = "Es"
subscription_content = "Subscribe now to get notified about exclusive News And Views Issues every week!"
subscription_title = "Rejoignez Newteller pour les dernières nouvelles"
weight = 1
[markup.goldmark.renderer]
unsafe = true
[[menu.footer]]
URL = "privacy-policy"
name = "privacy policy"
weight = 2
[[menu.footer]]
URL = "contact"
name = "contact"
weight = 1
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 3
[[menu.main]]
URL = "privacy-policy"
name = "Privacy Policy"
weight = 2
[[menu.main]]
URL = "about"
name = "About"
weight = 1
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
author = "Themefisher"
contact_form_action = "#"
description = "This is meta description"
google_analitycs_id = ""
logo = "images/logo.png"
sidebar = "left"
[params.instafeed]
access_token = "4044026246.1677ed0.8896752506ed4402a0519d23b8f50a17"
enable = true
user_id = "4044026246"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[[params.plugins.js]]
link = "plugins/instafeed/instafeed.min.js"
[params.preloader]
enable = false
preloader = ""
[params.promotion]
enable = true
image = "images/promotion.png"
link = "#"
[params.subscription]
enable = true
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074"
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"
[[params.social]]
icon = "ti-facebook"
link = "#"
title = "facebook"
[[params.social]]
icon = "ti-twitter-alt"
link = "#"
title = "twitter"
[[params.social]]
icon = "ti-instagram"
link = "#"
title = "instagram"
[[params.social]]
icon = "ti-github"
link = "#"
title = "github"
[[params.social]]
icon = "ti-linkedin"
link = "#"
title = "linkedin"
