baseURL = "/"
disableLanguages = []
disqusShortname = "n00b2h4ck3r"
paginate = "3"
summaryLength = "20"
theme = "gojournal"
title = "elblogdebraian | un blog para encontrarse con Dios"
[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com)"
home = "Home"
languageCode = "en-us"
languageName = "En"
subscription_content = "Subscribe now to get notified about exclusive News And Views Issues every week!"
subscription_title = "Join Newteller for the latest news"
weight = 2
[Languages.es]
contentDir = "content/spanish"
copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com)"
home = "Inicio"
languageCode = "es-es"
languageName = "Es"
subscription_content = "Subscribe now to get notified about exclusive News And Views Issues every week!"
subscription_title = "Rejoignez Newteller pour les dernières nouvelles"
weight = 1
[markup.goldmark.renderer]
unsafe = true
[[menu.footer]]
URL = "privacy-policy"
name = "privacy policy"
weight = 2
[[menu.footer]]
URL = "contact"
name = "contact"
weight = 1
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 3
[[menu.main]]
URL = "privacy-policy"
name = "Privacy Policy"
weight = 2
[[menu.main]]
URL = "about"
name = "About"
weight = 1
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
author = "Themefisher"
contact_form_action = "#"
description = "This is meta description"
google_analitycs_id = ""
logo = "images/logo.png"
sidebar = "left"
[params.instafeed]
access_token = "4044026246.1677ed0.8896752506ed4402a0519d23b8f50a17"
enable = true
user_id = "4044026246"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[[params.plugins.js]]
link = "plugins/instafeed/instafeed.min.js"
<<<<<<< HEAD


############################## navigation ###############################

# main menu
[[menu.main]]
name = "About"
URL = "about"
weight = 1

[[menu.main]]
name = "Privacy Policy"
URL = "privacy-policy"
weight = 2

[[menu.main]]
name = "More Hugo Theme"
URL = "https://gethugothemes.com/shop/"
weight = 2
  
[[menu.main]]
name = "Contact"
URL = "contact"
weight = 4

# footer menu

[[menu.footer]]
name = "contact"
URL = "contact"
weight = 1


[[menu.footer]]
name = "privacy policy"
URL = "privacy-policy"
weight = 2

#################### default parameters ################################
[params]
logo = "images/elblogdebraian.png"
# Meta data
description = "This is meta description"
author = "Themefisher"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = "UA-111733774-1" # your id
# sidebar
sidebar = "left" #sidebar value (left,right,false)

# Preloader
=======
>>>>>>> 17222f78355c19003313d77a9194a0782df16dde
[params.preloader]
enable = false
preloader = ""
[params.promotion]
enable = true
image = "images/promotion.png"
link = "#"
[params.subscription]
enable = true
<<<<<<< HEAD
user_id = "17841404309251338"
access_token = "bgaisy4mqpeey00j46um"
  
############################# social site ########################
=======
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074"
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"
>>>>>>> 17222f78355c19003313d77a9194a0782df16dde
[[params.social]]
icon = "ti-facebook"
link = "#"
title = "facebook"
[[params.social]]
<<<<<<< HEAD
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "https://www.facebook.com/braianagustin.diez/"

[[params.social]]
title = "instagram"
icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
link = "https://www.instagram.com/elblogdebraian/"

[[params.social]]
title = "github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "https://www.github.com/linuxmobile/"

[[params.social]]
title = "twitter"
icon = "ti-twitter" # themify icon : https://themify.me/themify-icons
link = "https://www.twitter.com/linuxmobileok/"


################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
# subscription
subscription_title = "Join Newteller for the latest news"
subscription_content = "Subscribe now to get notified about exclusive News And Views Issues every week!"
# copyright
copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com)"


################################### French language #####################################
[Languages.es]
languageName = "Es"
languageCode = "es-es"
contentDir = "content/spanish"
weight = 2
home = "Inicio"
# subscription
subscription_title = "Rejoignez Newteller pour les dernières nouvelles"
subscription_content = "Subscribe now to get notified about exclusive News And Views Issues every week!"
# copyright
copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com)"
=======
icon = "ti-twitter-alt"
link = "#"
title = "twitter"
[[params.social]]
icon = "ti-instagram"
link = "#"
title = "instagram"
[[params.social]]
icon = "ti-github"
link = "#"
title = "github"
[[params.social]]
icon = "ti-linkedin"
link = "#"
title = "linkedin"
>>>>>>> 17222f78355c19003313d77a9194a0782df16dde
