---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Blog Post
- type: directory
  path: exampleSite/content/english/post
  label: Post (en)
  create: documents
  match: "**/*"
  templates:
  - post
- type: directory
  path: exampleSite/content/french/post
  label: Post (fr)
  create: documents
  match: "**/*"
  templates:
  - post
- type: heading
  label: Others Pages
- type: directory
  path: exampleSite/content/english/about
  label: About (en)
  create: none
  match: "*"
- type: directory
  path: exampleSite/content/french/about
  label: About (fr)
  create: none
  match: "*"
- type: directory
  path: exampleSite/content/english/contact
  label: Contact (en)
  create: none
  match: "*"
- type: directory
  path: exampleSite/content/french/contact
  label: Contact (fr)
  create: none
  match: "*"
- type: directory
  path: exampleSite/content/english/privacy-policy
  label: Privacy Policy (en)
  create: none
  match: "*"
- type: directory
  path: exampleSite/content/french/privacy-policy
  label: Privacy Policy (fr)
  create: none
  match: "*"
- type: directory
  path: exampleSite/content/english
  label: All Pages (en)
  create: all
  match: "**/*"
  templates:
  - new-page
- type: directory
  path: exampleSite/content/french
  label: All Pages (fr)
  create: all
  match: "**/*"
  templates:
  - new-page
- type: heading
  label: Configuration
- type: directory
  path: exampleSite
  label: Configuration
  create: all
  match: "*.toml"
  new_doc_ext: toml
- type: directory
  path: exampleSite/i18n
  label: i18n translations
  create: documents
  match: "**/*"
upload_dir: exampleSite/static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.58.2
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.58.2
